language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "YZwL9HpoebTYYyf3e/GqADTuYhDXYQ+Zxmy4375T9o0EuydFhdzHSpCFHYqSBrsFzRfFmCKYSAUxMmAk9KaE3dHR6KZ6uNVSjEOokKzDGXRydnrRm0HA15octbdtKJLVsy0uZlFxGgMty88ylb5ICKLTmNNsTp1NwWbCasavc5c58Mok4ZaArRSALjR/mUAwYF1P2AOg6iQ8pj+MXdvcb8vnFI1AIFA3KVBAN/cHvrytxUUgir5rM9EsNoSG/oBYUEe5g41NpswMxVoT3U7L6K5kEePVbllFPhwp0LoIz3cW4tY0juaH+2QL6OqWOhKqUXhONOAjiXYbg8nUs2rFP4OnAzR8mFczc5kojuCb9MnJ6EgZKbrhFO5a23IT3UCM0XGCb2LQl2XQ2v2NhGPEpCRAIR+9kktcIOvbo7Q9a6thgvr/xH3PSks3DqL34EIEHk+nXVyQZTM2TahZjzen9MmtHzyQe9Lc38DS3W9GTgYdcuzmF/HSFdmITExWvNy+KXuVkkdFK5hjyBiCycWfJZKJL1FcoJ0VcYlKFxRmaxCveHuDHoMFD4hNjNaGgUJ5XYjp7LfSrAOtnAqEMABxBNUjGFBoHLnnl79pE7qbuZ0ZTIvHzh2vysDtNdpwlfBlCUXDvQMcerKFR43wiXX/rbmoDcby0NbVWt6VS69hGDQ="
env:
  secure: "FBLov4lK617az220rpU5FNXf8e0O35/4QLXEltGrkkOsjRGVDO2U9Y/8x2EzDu8DSi5he6H7ce3SK7H95QkWMFK+23DSfCG+eGTo7UVQqPmSajbQlwYAmiIAyjoN0q6u8yqiOMv3Td9r8YHiTsSb5v6oanAi0/eOU1A5IGFP62HjUPfNGG5gud/RWoRH2nD+852SWohkFYIDVou1ZDQyTlJq3kcFywEmLNG64PPvXYffJxtLzhr4qgHsuioc4SFDjHtP5Q+yL53zgDVWOOaXs9EJGdzKpbL5A1+2gZFfyh+bhtynhz1n5Ix5iu/Cn6Djr/6GpGr//5mCuKoZ7u8exU3cyM5pGHdIQuumV+i0WRIviuUQ8nPymLFBf0aH374PVAefUSvETR103aOjpdQPr1WOrlucDZWUxz9Ll5GzUXKGoEyFGMFWklc2BlXOsTUr/cxzFUOgJEKBMWUr4C/iGBkEfxmYAHxzvd51Y4Zm0LN/buXxVSnftnrcrlN1/cYtcGuSSIDKmBh4G5zKRgk/eYAeqV7M0TiIBuDhqtWt63Uzpp5FINxP40wA7/VS2tqKJaoWhXXkZzgpczZt2qZFDc7yEO5K54DychkgUjHbiRJlOJ3rLt7u32UKVynNZIZ9w/BP7yNKt5UEqXb/isZMkfUpJAcuhZX+L3i0OHiFXv0="
