language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: YmpPyv+Bb+k/gx/OOe3SThscHO5RVWLKl5J+qqrdE/Jdu7iG+F5VMj9ajtwY73t26Dv4HqBexV/gXq/6N2z09iPK3EGjCqcU7sn1MAgDzZHkks4x/ADt/pVcZEdaEMBA6QpKH7afFH/SKHw2n0Hp9q9MQhXzuoyvmPx6ahPzRAmaF5JQ142rQzRXMQ3pqeeVI+6jsKelwxb2NZYefz6LlkDoaNjUPXbgO4DLWwzxWbRtWpQH8J/IBR3enoWuTPfOVq/Thiq/jDeME+YeY/kcwAOJweLSLaO1nEFDIvGXO+kL4BWxgDxMwlo8avleIxvluOJXKhC5EyAfF9ASytZPUqAaQMmzV/jefkas9EW+A/Kp46hMjZFbs8pHTjHp3zPjfXPdTQJTLs9KhdgHQstz14BwtXzIZ43/wmnSViJ8jYut8sSylconAhDIdRHNc5pONHSxfXjYfIe2nSEh5KiyXdsb27t2oi5It9kGDdV6wUz2SazDE4io64Fsl5l+AznO5f4Abmztydoa6HdEof01isCOtEU1+OZktoh2yxA9xJ7woNUc1rKqJ4RtNP4yWUY6R52qaZBo0hSD4Ymaf//86z+mChukdVsnJ6Hnf+AE8J3BVtRQ5UtqdaT13/RV9YhPuKbsm1N90zS4uFv93V5oYu1Db527W1uH4KG/KMS0Muo=
